#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2015 ITCase <info@itcase.pro>
#
# Distributed under terms of the MIT license.

language: node_js

notifications:
  email: "arkadiy@bk.ru"
  email: "ggift@mail.ru"

node_js:
  - "0.12"
  - "iojs"

script:
  - nosetests --with-coverage --cover-package pyramid_sacrud --cover-erase --with-doctest

after_success:
  - npm test
