#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2015 ITCase <info@itcase.pro>
#
# Distributed under terms of the MIT license.

language: node_js

notifications:
  email: "arkadiy@bk.ru"

node_js:
  - "0.10"

sudo: false

env:
  global:
    - NODE_ENV=travisci

before_script:
  - npm install

script:
  - mocha -b --timeout 999999 tests/