#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2015 ITCase <info@itcase.pro>
#
# Distributed under terms of the MIT license.

language: node_js

notifications:
  email: "arkadiy@bk.ru"

node_js:
  - "0.10"

sudo: false

env:
  global:
    - NODE_ENV=travisci
    - NODE_ENV=test

before_script:
  - npm install --dev

script:
  - mocha --timeout 999999 tests

after_script:
   - istanbul cover node_modules/mocha/bin/_mocha -- tests/ -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage